### PR TITLE
Remove Bitwise warning on compilation

### PR DESCRIPTION
**Pull request by sleipnir**
Use import instead of use.
Mix format

### CODE REVIEW

**Comment by mmmries** [comment]
❤️ 💛 💙 💚 💜 Thank you for the contribution. I've been meaning to add CI to make sure we keep this library working for multiple versions of elixir/otp. I'll try to branch from your changes and get that running

**Comment by sleipnir** [comment]
Hi @mmmries !

Cool, I took the liberty of including a simple pipeline that runs tests on different versions of OTP. If you find it unnecessary to do this PR, I can undo it

**Comment by mmmries** [comment]
Extra awesome! Thanks for providing the CI setup. I'll go ahead and merge and then maybe add a few elixir versions to the matrix in a follow-on PR to make sure that the move from `use` to `import` works well for elixir versions 1.10+

**Comment by mmmries** [comment]
Extra awesome! Thanks for providing the CI setup. I'll go ahead and merge and then maybe add a few elixir versions to the matrix in a follow-on PR to make sure that the move from `use` to `import` works well for elixir versions 1.10+

**Comment by mmmries** [comment]
Thanks again, for pushing this up. I added on testing a wider range of elixir versions and then published version `0.2.2` on hex with these changes in place.

**Comment by sleipnir** [comment]
Great! Thank you so much @mmmries

**Pull request merged**
